version: "2"

services:

  postgresdb:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - '5432:5432'
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./dbbackup:/dbbackup

  api:
     engine: golang
     engine.config:
     package: nanobox-beego
     depends_on:
- postgresdb
